name: Deploy to server
on:
  push:
    branches: ["main"]
jobs:
  first-job:
    name: "Tutorial codigo facilito"
    runs-on: ubuntu-latest

    env:
      NAME: "CODIGO FACILITO"

    steps:
      - name: Hola mundo
        run: echo "Hola mundo $NAME"

      - name: working dir
        id: step_1
        run: echo "my_variable=Hola mundo" >> $GITHUB_OUTPUT

      - name: Action
        uses: actions/checkout@v2
      
      - name: obtener step_1
        run: echo "${{ steps.step_1.outputs.my_variable }}" 
  
  second-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: first-job

    steps:
      - name: Hola mundo 2
        run: echo "Hola mundo 2"

