name: Deploy to server
on:
  push:
    branches: ["main"]

jobs:
  first-job:
    name: "Tutorial codigo facilito"
    runs-on: ubuntu-latest

    env:
      NAME: "CODIGO FACILITO"

    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}

    steps:
      - name: Hola mundo
        run: echo "Hola mundo $NAME"

      - name: working dir
        id: step_1
        run: echo "my_variable=Hola mundo" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v2

      - name: obtener step_1
        run: echo "${{ steps.step_1.outputs.my_variable }}"
  
  second-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: first-job

    steps:
      - name: Hola mundo 2
        run: echo "Hola mundo 2"

  third-job: 
    runs-on: ubuntu-latest
    needs: second-job

    steps:
      - name: Generar archivo
        run: |
          echo "Este es un archivo generado por el tercer job" >> test.log
      
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-artifact
          path: test.log
  
  fourth-job:
    runs-on: ubuntu-latest
    needs: third-job

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: archivo-artifact
      
      - name: Mostrar contenido del archivo
        run: cat test.log