name: Deploy to server
on:
  push:
    branches: ["main"]
jobs:
  first-job:
  runs-on: ubuntu-latest
  
  steps:
    - name: Hola mundo
      run: echo "Hola mundo"
  
  second-job:
    runs-on: ubuntu-latest
    needs: first-job

    steps:
      - name: Hola mundo 2
        run: echo "Hola mundo 2"

